### ISSUE TITLE
PermissionDispatcher v3.0.1 failed

### ISSUE THREAD

**Issue by bsoykal** [permissions-dispatcher/AndroidAnnotationsPermissionsDispatcherPlugin#13]
Cannot use with PermissionDispatcher library v3.0.1 , they have changed the generated method names therefore the generated class cannot find the method.

 DashBoardActivityPermissionsDispatcher.**startLocationUpdatesWithCheck**(this); -> failed

Thanx Bro 👍

**Comment by hotchemi** [comment]
Yeah, we need an update!

**Comment by AleksanderMielczarek** [comment]
Version 2.1.0 has Kotlin support.
