### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by AleksanderMielczarek** [permissions-dispatcher/AndroidAnnotationsPermissionsDispatcherPlugin#15]
Plugin needs to support Kotlin:
- rewrite plugin in Kotlin
- detect Kotlin or Java and generate appropriate code

@hotchemi did I miss something?

**Comment by hotchemi** [comment]
> rewrite plugin in Kotlin

Kool!

> detect Kotlin or Java and generate appropriate code

Not sure it's possible but I think that's right 😄 

Thx~!

**Comment by AleksanderMielczarek** [comment]
> Not sure it's possible

Is this line responsible for that?

```Kotlin
if (kotlinMetadata != null) {
    processKotlin(it, rpe, requestCodeProvider)
} else {
    processJava(it, rpe, requestCodeProvider)
}
```

**Comment by hotchemi** [comment]
Ah yes! but I'm not sure we can use the same logic in the lib 😺

**Comment by mortenholmgaard** [comment]
Any news on when it will be possible to use Kotlin with it?
