### ISSUE TITLE
Provide a config way to disable delegates and overrides auto generating

### ISSUE THREAD

**Issue by luongvo** [permissions-dispatcher/AndroidAnnotationsPermissionsDispatcherPlugin#18]
When I using this plugin to enable permissions-dispatcher (PD) working with AA on my project, I met some issues with delegates and overrides auto generating (described at https://github.com/permissions-dispatcher/AndroidAnnotationsPermissionsDispatcherPlugin#migrating-to-2xx).

Please check out my issue example repo at: https://github.com/luongvo/AndroidAnnotationsPermissionsDispatcherPlugin/commit/f60f550e16191f962e6b1363c14530f0a45854a3

- I implemented PD in `MainActivity` abstract class, `MainActivityPermissionsDispatcher` will be generated, but no `MainActivity_`, that's right.
- Then extends it to `ChildMainActivity` without PD implemented, `ChildMainActivityPermissionsDispatcher` will not be generated, but has `ChildMainActivity_`. This plugin still generates delegates and overrides in `ChildMainActivity_`. After processed, it failed with `error: cannot find symbol variable ChildMainActivityPermissionsDispatcher` in `ChildMainActivity_`.

So:
- Please provide the way to disable this generating
- Or, do not generate `ChildMainActivityPermissionsDispatcher` invoke in `onRequestPermissionsResult` if it has no annotation, also for those methods which was annotated with `@NeedsPermission`

**Comment by AleksanderMielczarek** [comment]
Thanks for the info. I'll take a look on that.

**Comment by AleksanderMielczarek** [comment]
Fixed in 2.1.1. Plugin won't generate dispatcher calls for class without `@RuntimePermissions`.

**Comment by luongvo** [comment]
@AleksanderMielczarek So fast, thanks 🚀
