### ISSUE TITLE
NeedsPermission in abstract class

### ISSUE THREAD

**Issue by SnyersK** [permissions-dispatcher/AndroidAnnotationsPermissionsDispatcherPlugin#19]
Hi!

My case is the following:

I have a `BaseDetailFragment`, that contains some shared logic for my `PhoneDetailFragment` and `TabletDetailFragment`.

One of these things, is managing the options menu.
For a couple of my options items, I need certain permissions.

I would like to handle these with the `PermissionDispatcher`.
I see the dispatcher is generated, however, it is not used by the AA generated `PhoneDetailFragment_`.

Is there something I can do to make this work, or is this impossible?

My code looks like this:

```
@EFragment
@RuntimePermissions
@OptionsMenu(R.menu.detail_menu)
public abstract class BaseDetailFragment extends Fragment {

    @OptionsItem(R.id.share)
    @NeedsPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
    protected void onShareClicked() {
        // some code
    }

}

@EFragment(R.layout.fragment_detail)
public class PhoneDetailFragment extends BaseDetailFragment {
    //No other permissions needed here
}
```

Thanks in advance!

**Comment by WonderCsabo** [comment]
Try adding `@RuntimePermissions` to  `PhoneDetailFragment` as well?

**Comment by hotchemi** [comment]
@SnyersK at the moment we don't support abstract class. Annotate PhoneDetailFragment and TabletDetailFragment is a way to go.
