### ISSUE TITLE
Will not work with PermissionDispatcher 4.2.0 +

### ISSUE THREAD

**Issue by WonderCsabo** [permissions-dispatcher/AndroidAnnotationsPermissionsDispatcherPlugin#21]
The upstream project changed the package name. https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/560

This plugin should follow that change as well.

**Comment by WonderCsabo** [comment]
Sorry, false positive. The package name was already `permissions.dispatcher`.

**Comment by hotchemi** [comment]
ah yea🙇We're going to publish this to jcenter as well with the same groupID.
